name: CI/CD Pipeline

on:
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run tests
      run: |
        echo "Running tests..."
        # Thêm lệnh chạy test của bạn ở đây
        # Ví dụ: python -m pytest
        
    - name: Run linting
      run: |
        echo "Running linting..."
        # Thêm lệnh chạy linting của bạn ở đây
        # Ví dụ: flake8, black --check, etc.
        
    - name: Run security checks
      run: |
        echo "Running security checks..."
        # Thêm lệnh chạy security checks của bạn ở đây
        
  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build application
      run: |
        echo "Building application..."
        # Build Python package
        python setup.py build
        # Hoặc nếu dùng pip
        # pip install build
        # python -m build
        # Hoặc nếu dùng poetry
        # poetry build
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: |
          dist/
          build/
          
  deploy-staging:
    runs-on: ubuntu-latest
    needs: [test, build]
    
    steps:
    - name: Deploy to staging
      run: |
        echo "Deploying to staging environment..."
        # Thêm lệnh deploy staging của bạn ở đây
