name: SQL Validation on PR Approval

on:
  pull_request_review:
    types: [submitted]
    branches: [ main, master ]

jobs:
  validate-sql:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        
    - name: Run SQL validation
      run: |
        echo "🔍 PR Approved - Running SQL validation..."
        python work.py
