name: SQL Syntax Check on PR Approval

on:
  pull_request:
    types: [review_requested, submitted]
    branches: [ main, master ]

jobs:
  check-sql-syntax:
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
        
    - name: Check SQL Syntax
      run: |
        echo "🔍 Checking SQL syntax after PR approval..."
        
        # Find all SQL files
        SQL_FILES=$(find . -name "*.sql" -type f)
        
        if [ -n "$SQL_FILES" ]; then
          echo "📁 Found SQL files:"
          echo "$SQL_FILES"
          echo ""
          
          # Check each SQL file
          for file in $SQL_FILES; do
            echo "✅ Checking: $file"
            echo "   Size: $(wc -c < "$file") bytes"
            echo "   Lines: $(wc -l < "$file") lines"
            
            # Basic SQL syntax check (check if file is readable)
            if [ -r "$file" ]; then
              echo "   Status: ✅ File readable"
            else
              echo "   Status: ❌ File not readable"
              exit 1
            fi
            
            # Check if file has content
            if [ -s "$file" ]; then
              echo "   Status: ✅ File has content"
            else
              echo "   Status: ❌ File is empty"
              exit 1
            fi
            
            echo ""
          done
          
          echo "🎉 All SQL files passed syntax check!"
        else
          echo "⚠️  No SQL files found in this PR"
        fi
        
    - name: Success Status
      if: success()
      run: |
        echo "✅ SQL Syntax Check: PASSED"
        echo "All SQL files are valid and ready for review"
        
    - name: Failure Status
      if: failure()
      run: |
        echo "❌ SQL Syntax Check: FAILED"
        echo "Please fix the issues before merging"
        exit 1
