select * from users;
select * from products;
select * from orders;
select * from order_items;
select * from customers;
select * from suppliers;
select * from categories;
select * from products;
select * from products;